### PR TITLE
Retain comments in the feeds file

### PR DESCRIPTION
**Pull request by DaleFarnsworth**
We assume that all comment and blank lines in the feeds file are
associated with the feed url that follows them.  We maintain
those comments and list or delete them when the url is listed
or deleted.  When a new feed url is added, a comment is added
that consists of the feed's Title.

These default Title comments can be created for a current feedlist
by the following command:
    cd ~/.rss2email && mv feeds feeds.tmp &&
        rss2email add $(grep '^[^#]' feeds.tmp) && rm feeds.tmp

### CODE REVIEW

**Comment by DaleFarnsworth** [comment]
Well, it's consistent.  But I still don't know what check is failing.

**Comment by skx** [comment]
> Well, it's consistent. But I still don't know what check is failing.

I assumed you could see the failure, but I'm a little hazy on the actions.  You need to click on the `Fail` thing, and scroll down.  For reference the failure is:

```
frodo ~/Repos/github.com/skx/rss2email $ golint ./...
feedlist/feedlist.go:88:27: exported func New returns unexported type *feedlist.feedList, which can be annoying to use
```

I'm not sure whether it is complaining about stuttering-name `the.the`,  or the fact the return value is unexported (i.e. `feedList` vs `FeedList`).  But I can look properly later.

I'm not a huge fan of the comment-handling, though shuffling the code around to move the URL-fetching is a positive change.  I'd merge, but I'm a little skeptical of automagic association of comments, I suspect that we should just say "Comments not supported" to be honest.  But I have no idea what other people do.  I can imagine that some people use them for sensible purposes.

**Comment by DaleFarnsworth** [comment]
I had tried to click on everything in sight, without seeing the failure.  But now I found where I could click and see the golint error message.  I've installed golint and revised the patch.

I think the feed titles improve the feeds listing:
```
rss2email list

# Dangerous Prototypes
http://dangerousprototypes.com/blog/feed/

# Screaming Circuits
http://feeds.feedburner.com/ScreamingCircuits

# Linux and Microcontroller Tips
http://feeds.feedburner.com/shibuvarkala

# Geek Circuits
http://geekcircuits.com/feed/

# Embedded Microcontroller Programming
http://mcu-programming.blogspot.com/feeds/posts/default

# MightyOhm
http://mightyohm.com/blog/feed/

# PIC Microcontroller Note
http://picnote.blogspot.com/feeds/posts/default

# Hackaday
https://hackaday.com/feed/

# Let's Encrypt - Free SSL/TLS Certificates
https://letsencrypt.org/feed.xml

# Electronics Weekly
https://www.electronicsweekly.com/feed/

# Hiawatha webserver weblog
https://www.hiawatha-webserver.org/weblog.xml

# Blog – Linode
https://www.linode.com/blog/feed/
```
I've fixed the golint warnings and repushed the branch.  Thanks!

**Comment by DaleFarnsworth** [comment]
The titles were added automatically by rss2email.  I doubt that I would ever hand-edit the feeds file, but if I were to do so, the comments would be retained and displayed by "rss2email list".

**Pull request merged**
