### PR TITLE
Allow the email template to be replaced

### LINKED ISSUE #16: Put feed.Title into the From: address?
I'm using the below patch so that my feed emails have the title of the feed in the sender address. If the passed sender address contains the string "{{FeedTitle}}", that string is replaced by the actual feed title.  Something like:
  rss2email cron -from="{{FeedTitle}} <email@mydomain.com>" email@mydomain.com
I'm happy with the result, but not sure the UI is the best.

```
diff --git a/cron_cmd.go b/cron_cmd.go
index 08755b1..f7b48c6 100644
--- a/cron_cmd.go
+++ b/cron_cmd.go
@@ -70,6 +70,8 @@ func (p *cronCmd) ProcessURL(input string) error {
                fmt.Printf("\tFound %d entries\n", len(feed.Items))
        }
 
+       fromAddr := strings.Replace(p.fromAddr, "{{FeedTitle}}", "\"" + feed.Title + "\"", 1)
+
        // For each entry in the feed ..
        for _, i := range feed.Items {
 
@@ -102,7 +104,7 @@ func (p *cronCmd) ProcessURL(input string) error {
                                text := html2text.HTML2Text(content)
 
                                // Send the mail
-                               err := SendMail(input, p.fromAddr, p.emails, i.Title, i.Link, text, content)
+                               err := SendMail(input, fromAddr, p.emails, i.Title, i.Link, text, content)
                                if err != nil {
                                        return err
                                }
```

### PR DESCRIPTION
**Pull request by skx**
This pull-request makes it possible for users to override the
default template which is used to generate the email.

This replaces #17, and closes #16 by making it possible for
users to make that choice for themselves.

### CODE REVIEW

**Comment by DaleFarnsworth** [comment]
This branch meets my needs.  Thank you.

Four comments.
  1. If you terminate the template comment with " -}}", the whitespace following it is stripped, so you can start the template text on the next line.

  2. With a configurable template, we don't really need fromAddr anymore.

  3. I have no interest in the value of {{now}}.  I am interested in the item published date.  I'd be happy with the string produced by i.PublishedParsed.Format(RFC822Z).  Or, for maximum flexibility, pass i.PublishedParsed along with a function to do time.Format.  It would have been nice to use i.Published, but the format varies with the feed, and some formats are not very user friendly.

  4. You might consider passing i (withstate.FeedItem) to SendMail() and move the assignment of content and text to within SendMail().

**Comment by DaleFarnsworth** [comment]
On further reflection, having the item published date is of such limited value that I think it's not worth doing.  I'm sorry for bringing it up in the first place.  I still think we can remove {{now}}. :-)

**Comment by DaleFarnsworth** [comment]
It would be nice to name the template "email.tmpl", as in template.New("email.tmpl") so that the error message contains the filename on parse errors.

**Comment by skx** [comment]
* With a configurable template, we don't really need fromAddr anymore.

Yes, removed on that basis.

* I have no interest in the value of {{now}}. I am interested in the item published date. I'd accept the string produced by..

I was using the shortcut that cron runs every N minutes, so the current time is a reasonable proxy for the actual publication date.  Still it was a bit rough and ready.   I've updated the template to explicitly pass `RSSFeed` and `RSSItem` so that access to fields can be done in the template.  Annoyingly the test-feeds i'm using have nothing useful there.  Hrm.

* You might consider passing i (withstate.FeedItem) to SendMail() and move the assignment of content and text to within SendMail().

Yeah that's an area that needs some thought; the email sending is currently mixing too many concerns and should be cleaned up.  I'll postpone that for the moment though.

* It would be good to move the call to i.RecordSeen() after the attempt to send email, so that if the attempt fails, we could retry sending the email later.

Good suggestion.  Done.

**Comment by DaleFarnsworth** [comment]
I still like this change.  It's purely cosmetic though.

```
diff --git a/data/email.tmpl b/data/email.tmpl
index c404428..9cbf0ae 100644
--- a/data/email.tmpl
+++ b/data/email.tmpl
@@ -21,7 +21,9 @@
 
      This comment will be stripped from the generated email.
 
-  */}}Content-Type: multipart/mixed; boundary=21ee3da964c7bf70def62adb9ee1a061747003c026e363e47231258c48f1
+  */ -}}
+
+Content-Type: multipart/mixed; boundary=21ee3da964c7bf70def62adb9ee1a061747003c026e363e47231258c48f1
 From: {{.From}}
 To: {{.To}}
 Subject: [rss2email] {{.Subject}}
```

I won't mention it again though.  :-)

**Comment by DaleFarnsworth** [comment]
Thank you for being so responsive to my requests/comments.  rss2email has all the features I can think of.  My feed emails look exactly the way I want them without any local patches.  Thanks again!

**Comment by skx** [comment]
Sorry somehow I spaced out reading your feedback and missed that bit.  Fixed now.

And no problem, it's been a fun few days.  I'll take a new release shortly, and then leave the project to stall for a few more months!

**Comment by DaleFarnsworth** [comment]
Sounds like a plan!

**Pull request merged**
