### PR TITLE
Dockerfile improvements

### PR DESCRIPTION
**Pull request by visit1985**
- use non-root user to run rss2email
- install binary to PATH
- fixed entrypoint

Let me know if this raises any concerns. 

Thanks for your work!

### CODE REVIEW

**Comment by faan11** [comment]
any news about these changes? LGTM @skx

**Comment by skx** [comment]
Somehow I'd managed to gloss over this.

I'll test it out tonight, but at an initial look it seems reasonable - thanks for the reminder.

**Comment by StayPirate** [comment]
Tested on my side as well. It works great, but it required me to manually jump into the associated docker named-volume and change the owner of all persistent files: `chmod -R app:app .rss2email`.

**Comment by skx** [comment]
Same for me, sadly.  Took a moment to work out why I was seeing permission denied, but I guess I make a new release tomorrow and document this explicitly.

**Pull request merged**
