### PR TITLE
add ability to encode header entries

### PR DESCRIPTION
**Pull request by thoka**
Encode subject, if a feed contains non-ASCII characters.

### CODE REVIEW

**Comment by skx** [comment]
This seems reasonable, and useful,, at a quick glance.

I'll test and merge in a day or two, but busy here just now.

Thanks for your contribution :)

**Comment by visit1985** [comment]
This breaks the format of non-atom feed subjects for me.

https://aws.amazon.com/about-aws/whats-new/recent/feed/



Any ideas? Thanks in advance!

**Comment by skx** [comment]
Confirmed, I see the same thing.

If there's no update from @thoka within the next week I'll have to revert, and see if there is a middle-ground.

**Comment by thoka** [comment]
Hm. 

quotedprintable inserts soft line breaks (=\r\n), when line length exceeds 76 chars

Fixed in https://github.com/thoka/rss2email/commit/39de2c76e93fc74aba955d1114a7c9d921aaf380

**Comment by visit1985** [comment]
Thanks @thoka. I can confirm, that the fix works.

**Comment by skx** [comment]
Applied now, and released as [release-3.2](https://github.com/skx/rss2email/releases/tag/release-3.2)

**Pull request merged**
